version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: facet-php
    working_dir: /var/www/facet
    volumes:
      - .:/var/www/facet
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - facet-net

  nginx:
    image: nginx:alpine
    container_name: facet-nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/facet
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - facet-net

  mysql:
    image: mysql:8.0
    container_name: facet-mysql
    restart: always
    environment:
      MYSQL_DATABASE: facet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: facet
      MYSQL_PASSWORD: facet
    ports:
      - "33088:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - facet-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: facet-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9208:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - facet-net

volumes:
  mysql_data:
  esdata:

networks:
  facet-net:
    driver: bridge
